# Generated by Django 5.2 on 2026-03-18 14:11

import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('author_name', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
                ('price', models.FloatField(default=0.0)),
                ('picture1', models.ImageField(default=None, null=True, upload_to='images/')),
                ('picture2', models.ImageField(default=None, null=True, upload_to='images/')),
                ('picture3', models.ImageField(default=None, null=True, upload_to='images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='book_name', unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BookForSell',
                'ordering': ['book_name', 'author_name'],
            },
        ),
    ]
