# Generated by Django 5.2 on 2026-03-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_for_sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookforsell',
            name='picture1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bookforsell',
            name='picture2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bookforsell',
            name='picture3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
