# Generated by Django 5.2 on 2026-03-18 14:11

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForLend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=30)),
                ('picture1', models.ImageField(upload_to='images/')),
                ('picture2', models.ImageField(upload_to='images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='book_name', unique=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BookForLend',
                'ordering': ['book_name', 'author_name'],
            },
        ),
    ]
