# Generated by Django 5.2 on 2026-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'USER',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
