# Generated by Django 5.2 on 2026-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mycustomuser_is_active_mycustomuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
